package eu.europa.ec.etrustex.integration.gateway;

import ec.services.wsdl.document_1.FaultResponse;
import ec.services.wsdl.document_1.ObjectFactory;
import ec.services.wsdl.document_1.SubmitDocumentRequest;
import ec.services.wsdl.document_1.SubmitDocumentResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-20T14:16:46.437+01:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "ec:services:wsdl:Document-1", name = "submitDocumentPortType")
@XmlSeeAlso({oasis.names.specification.ubl.schema.xsd.signaturebasiccomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.fault_1.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ObjectFactory.class, ec.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, org.etsi.uri._01903.v1_4.ObjectFactory.class, ec.schema.xsd.commonbasiccomponents_1.ObjectFactory.class, org.etsi.uri._01903.v1_3.ObjectFactory.class, org.unece.cefact.namespaces.standardbusinessdocumentheader.ObjectFactory.class, un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.ObjectFactory.class, ec.schema.xsd.deletedocument_1.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.signatureaggregatecomponents_2.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.qualifieddatatypes_2.ObjectFactory.class, ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, oasis.names.specification.ubl.schema.xsd.commonaggregatecomponents_2.ObjectFactory.class, ec.schema.xsd.ack_2.ObjectFactory.class, org.w3._2005._05.xmlmime.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SubmitDocumentPortType {

    @WebMethod
    @WebResult(name = "SubmitDocumentResponse", targetNamespace = "ec:services:wsdl:Document-1", partName = "SubmitDocumentResponse")
    public SubmitDocumentResponse submitDocument(
            @WebParam(partName = "SubmitDocumentRequest", name = "SubmitDocumentRequest", targetNamespace = "ec:services:wsdl:Document-1")
                    SubmitDocumentRequest submitDocumentRequest,
            @WebParam(partName = "Header", mode = WebParam.Mode.INOUT, name = "Header", targetNamespace = "ec:services:wsdl:Document-1", header = true)
                    javax.xml.ws.Holder<ec.schema.xsd.commonaggregatecomponents_2.HeaderType> header
    ) throws FaultResponse;
}
