use etrustex;

ALTER TABLE ETR_TB_CREDENTIALS ADD CRED_SALTED tinyint(1) DEFAULT 0;
ALTER TABLE ETR_TB_CREDENTIALS ADD IV tinyblob;

ALTER TABLE ETR_TB_CERTIFICATE MODIFY CERT_HOLDER varchar(400);
ALTER TABLE ETR_TB_CERTIFICATE MODIFY CERT_ISSUER varchar(400);

ALTER TABLE ETR_TB_PARTY DROP KEY FK92B82CF1B9A0FD68;
ALTER TABLE ETR_TB_PARTY DROP FOREIGN KEY FK92B82CF1B9A0FD68;
ALTER TABLE ETR_TB_PARTY DROP COLUMN PTY_CERT_ID;

ALTER TABLE ETR_TB_ENDPOINT DROP COLUMN EDP_MSG_TYPE;
ALTER TABLE ETR_TB_ENDPOINT DROP COLUMN EDP_AUTH_FLAG;

ALTER TABLE ETR_TB_MESSAGE_PRIORITY DROP FOREIGN KEY FK_MP_CRED;
ALTER TABLE ETR_TB_MESSAGE_PRIORITY CHANGE MP_CRED_ID MP_SENDER_ID bigint(20);
ALTER TABLE ETR_TB_MESSAGE_PRIORITY ADD CONSTRAINT FK_MP_SENDER FOREIGN KEY (`MP_SENDER_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`);

CREATE TABLE `ETR_TB_MSG_BIN_VALUE` (
	`MSG_BIN_VAL_ID` bigint(20), 
	`MSG_BIN_VAL_VALUE` longblob, 
	 PRIMARY KEY (`MSG_BIN_VAL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ETR_TB_MESSAGE_BINARY ADD MSG_BIN_MSG_BIN_VAL_ID bigint(20) DEFAULT NULL;
ALTER TABLE ETR_TB_MESSAGE_BINARY ADD CONSTRAINT FK_MSG_BIN_MSG_BIN_VAL FOREIGN KEY (`MSG_BIN_MSG_BIN_VAL_ID`) REFERENCES `ETR_TB_MSG_BIN_VALUE` (`MSG_BIN_VAL_ID`);

ALTER TABLE ETR_TB_METADATA ADD MD_BUSINESSDOMAIN_ID bigint(20) DEFAULT NULL;
ALTER TABLE ETR_TB_METADATA ADD CONSTRAINT FK_METADATA_BD_FK FOREIGN KEY (MD_BUSINESSDOMAIN_ID) REFERENCES CPA_TB_BUSINESS_DOMAIN (CBD_ID);

DROP TABLE ETR_TB_SLA_POLICY;

CREATE TABLE `ETR_TB_HR_TEMPLATE` ( 
   	`HRT_ID` bigint(20), 
	`CRE_DT` datetime, 
	`CRE_ID` varchar(255), 
	`MOD_DT` datetime, 
	`MOD_ID` varchar(255), 
	`HRT_NAME` varchar(255), 
	`HRT_XSLT` longtext, 
	`HRT_DOC_ID` bigint(20), 
	`HRT_TRA_ID` bigint(20), 
	`HRT_IS_DEFAULT` tinyint(1) DEFAULT 0,
	PRIMARY KEY (`HRT_ID`),
	UNIQUE KEY `HRT_UNIQUE` (`HRT_NAME`, `HRT_DOC_ID`, `HRT_TRA_ID`),
	CONSTRAINT `FK_HR_TEMPLATE_TX` FOREIGN KEY (`HRT_TRA_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`), 
	CONSTRAINT `FK_HR_TEMPLATE_DOC` FOREIGN KEY (`HRT_DOC_ID`) REFERENCES `ETR_TB_DOCUMENT` (`DOC_ID`),
	KEY `HRT_IDX` (`HRT_NAME`, `HRT_DOC_ID`, `HRT_TRA_ID`)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_POLICY` (
	`POL_ID` bigint(20), 
	`CRE_DT` datetime, 
	`CRE_ID` varchar(255), 
	`MOD_DT` datetime, 
	`MOD_ID` varchar(255), 
	`POL_ACTIVE_FLAG` tinyint(1), 
	`POL_TRA_ID` bigint(20), 
	`POL_BD_ID` bigint(20), 
	`POL_TYPE` varchar(20), 
	`POL_FREQUENCY` varchar(20), 
	`POL_VALUE` bigint(20), 
	`POL_FLEXIBILITY` smallint, 
	 PRIMARY KEY (`POL_ID`),
	 CONSTRAINT `FK_POLICY_TX` FOREIGN KEY (`POL_TRA_ID`) REFERENCES .`ETR_TB_TRANSACTION` (`TRA_ID`), 
	 CONSTRAINT `FK_POLICY_BD` FOREIGN KEY (`POL_BD_ID`) REFERENCES .`CPA_TB_BUSINESS_DOMAIN` (`CBD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_JOB_DETAILS` (
   	`SCHED_NAME` varchar(120), 
	`JOB_NAME` varchar(200), 
	`JOB_GROUP` varchar(200), 
	`DESCRIPTION` varchar(250), 
	`JOB_CLASS_NAME` varchar(250), 
	`IS_DURABLE` varchar(1), 
	`IS_NONCONCURRENT` varchar(1), 
	`IS_UPDATE_DATA` varchar(1), 
	`REQUESTS_RECOVERY` varchar(1), 
	`JOB_DATA` BLOB, 
	PRIMARY KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
	KEY `ET2_IDX_QRTZ_J_GRP` (`SCHED_NAME`, `JOB_GROUP`),
	KEY `ET2_IDX_QRTZ_J_REQ_RECOVERY` (`SCHED_NAME`, `REQUESTS_RECOVERY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_TRIGGERS` (
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`JOB_NAME` varchar(200), 
	`JOB_GROUP` varchar(200), 
	`DESCRIPTION` varchar(250), 
	`NEXT_FIRE_TIME` bigint(13), 
	`PREV_FIRE_TIME` bigint(13), 
	`PRIORITY` bigint(13), 
	`TRIGGER_STATE` varchar(16), 
	`TRIGGER_TYPE` varchar(8), 
	`START_TIME` bigint(13), 
	`END_TIME` bigint(13), 
	`CALENDAR_NAME` varchar(200), 
	`MISFIRE_INSTR` tinyint(2), 
	`JOB_DATA` longblob, 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
	CONSTRAINT `FK2_TRIGGERS` FOREIGN KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`) REFERENCES `QRTZ2_JOB_DETAILS` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
	KEY `IDX_QRTZ2_T_C` (`SCHED_NAME`, `CALENDAR_NAME`),
	KEY `IDX_QRTZ2_T_G` (`SCHED_NAME`, `TRIGGER_GROUP`),
	KEY `IDX_QRTZ2_T_J` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
	KEY `IDX_QRTZ2_T_JG` (`SCHED_NAME`, `JOB_GROUP`),
	KEY `IDX_QRTZ2_T_NEXT_FIRE_TIME` (`SCHED_NAME`, `NEXT_FIRE_TIME`),
	KEY `IDX_QRTZ2_T_NFT_MISFIRE` (`SCHED_NAME`, `MISFIRE_INSTR`, `NEXT_FIRE_TIME`),
	KEY `IDX_QRTZ2_T_NFT_ST` (`SCHED_NAME`, `TRIGGER_STATE`, `NEXT_FIRE_TIME`),
	KEY `IDX_QRTZ2_T_NFT_ST_MISFIRE` (`SCHED_NAME`, `MISFIRE_INSTR`, `TRIGGER_STATE`, `NEXT_FIRE_TIME`),
	KEY `IDX_QRTZ2_T_NFT_ST_MISFIRE_GRP` (`SCHED_NAME`, `MISFIRE_INSTR`, `TRIGGER_STATE`, `NEXT_FIRE_TIME`, `TRIGGER_GROUP`), 
	KEY `IDX_QRTZ2_T_N_G_STATE` (`SCHED_NAME`, `TRIGGER_GROUP`, `TRIGGER_STATE`),
	KEY `IDX_QRTZ2_T_N_STATE` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`, `TRIGGER_STATE`),
	KEY `IDX_QRTZ2_T_STATE` (`SCHED_NAME`, `TRIGGER_STATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;	

CREATE TABLE `QRTZ2_BLOB_TRIGGERS` ( 
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`BLOB_DATA` longblob, 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
	CONSTRAINT `FK2_BLOB_TRIGGERS` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES .`QRTZ2_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_CALENDARS` (
   	`SCHED_NAME` varchar(120), 
	`CALENDAR_NAME` varchar(200), 
	`CALENDAR` BLOB, 
	PRIMARY KEY (`SCHED_NAME`, `CALENDAR_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_CRON_TRIGGERS` (
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`CRON_EXPRESSION` varchar(120), 
	`TIME_ZONE_ID` varchar(80), 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
	CONSTRAINT `FK2_CRON_TRIGGERS` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ2_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_FIRED_TRIGGERS` (
   	`SCHED_NAME` varchar(120), 
	`ENTRY_ID` varchar(95), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`INSTANCE_NAME` varchar(200), 
	`FIRED_TIME` bigint(13), 
	`SCHED_TIME` bigint(13), 
	`PRIORITY` bigint(13), 
	`STATE` varchar(16), 
	`JOB_NAME` varchar(200), 
	`JOB_GROUP` varchar(200), 
	`IS_NONCONCURRENT` varchar(1), 
	`REQUESTS_RECOVERY` varchar(1), 
	PRIMARY KEY (`SCHED_NAME`, `ENTRY_ID`),
	KEY `IDX_QRTZ2_FT_JG` (`SCHED_NAME`, `JOB_GROUP`),
	KEY `IDX_QRTZ2_FT_J_G` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
	KEY `IDX_QRTZ2_FT_RCVRY` (`SCHED_NAME`, `INSTANCE_NAME`, `REQUESTS_RECOVERY`),
	KEY `IDX_QRTZ2_FT_TG` (`SCHED_NAME`, `TRIGGER_GROUP`),
	KEY `IDX_QRTZ2_FT_TRIG_INST_NAME` (`SCHED_NAME`, `INSTANCE_NAME`),
	KEY `IDX_QRTZ2_FT_T_G` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_LOCKS` (
  	`SCHED_NAME` varchar(120), 
	`LOCK_NAME` varchar(40), 
	 PRIMARY KEY (`SCHED_NAME`, `LOCK_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;	 

CREATE TABLE `QRTZ2_PAUSED_TRIGGER_GRPS` (
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_GROUP` varchar(200), 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_SCHEDULER_STATE` (
   	`SCHED_NAME` varchar(120), 
	`INSTANCE_NAME` varchar(200), 
	`LAST_CHECKIN_TIME` bigint(13), 
	`CHECKIN_INTERVAL` bigint(13), 
	PRIMARY KEY (`SCHED_NAME`, `INSTANCE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_SIMPLE_TRIGGERS` (
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`REPEAT_COUNT` int, 
	`REPEAT_INTERVAL` bigint(12), 
	`TIMES_TRIGGERED` bigint(10), 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_SIMPROP_TRIGGERS` (
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`STR_PROP_1` varchar(512), 
	`STR_PROP_2` varchar(512), 
	`STR_PROP_3` varchar(512), 
	`INT_PROP_1` bigint(10), 
	`INT_PROP_2` bigint(10), 
	`LONG_PROP_1` bigint(13), 
	`LONG_PROP_2` bigint(13), 
	`DEC_PROP_1` decimal(13,4), 
	`DEC_PROP_2` decimal(13,4), 
	`BOOL_PROP_1` varchar(1), 
	`BOOL_PROP_2` varchar(1), 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

